// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEqTc34sALS4f2I7ks7BgYId51kqB07UA',
    appId: '1:45663027751:web:9d88fca45595331aba8402',
    messagingSenderId: '45663027751',
    projectId: 'zikrstudy',
    authDomain: 'zikrstudy.firebaseapp.com',
    storageBucket: 'zikrstudy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-3i3TpsDx4BJobTCxuGrvEQS4vrdn6Cs',
    appId: '1:45663027751:android:71bcbc9261fed031ba8402',
    messagingSenderId: '45663027751',
    projectId: 'zikrstudy',
    storageBucket: 'zikrstudy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT0FzH0eY7CTc_ZCpJCtLDXrp076kfq2I',
    appId: '1:45663027751:ios:134f5f9e199e39e2ba8402',
    messagingSenderId: '45663027751',
    projectId: 'zikrstudy',
    storageBucket: 'zikrstudy.appspot.com',
    iosClientId: '45663027751-0gru7jrulembqdqb9qlca9oag9h63pkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.alphaStudyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT0FzH0eY7CTc_ZCpJCtLDXrp076kfq2I',
    appId: '1:45663027751:ios:134f5f9e199e39e2ba8402',
    messagingSenderId: '45663027751',
    projectId: 'zikrstudy',
    storageBucket: 'zikrstudy.appspot.com',
    iosClientId: '45663027751-0gru7jrulembqdqb9qlca9oag9h63pkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.alphaStudyProject',
  );
}
